### ISSUE TITLE
You should add the text summaries

### ISSUE THREAD

**Issue by glassbase** [michaeldavie/env_canada#1]
I have been using your component for awhile now. I know it never got merged. Too bad. Canadian weather is always better served by Environment Canada (vs some US based weather service like DarkSky or Yahoo Weather). 

You should try and integrate the text summaries of the today forecast and maybe the tonight forecast and tomorrow forecast. That way others could use it to announce via TTS or other notifications.

As example, [Dark Sky](https://www.home-assistant.io/components/sensor.darksky/) has a monitored condition for `summary` = A human-readable text summary.

It is in the EC XML data
```
<forecastGroup>
<forecast>
<period textForecastName="Today">Monday</period>
<textSummary>
Increasing cloudiness. Snow beginning this afternoon. Amount 2 cm. Wind northeast 20 km/h gusting to 40. High minus 23. Wind chill minus 41 in the morning and minus 34 in the afternoon. Risk of frostbite. UV index 1 or low.
</textSummary>
...
</forecast>
<forecast>
<period textForecastName="Tonight">Monday night</period>
<textSummary>
Snow at times heavy. Local blowing snow overnight. Amount 10 to 15 cm. Wind east 30 km/h gusting to 50. Temperature rising to minus 16 by morning. Wind chill minus 34 in the evening and minus 25 overnight. Risk of frostbite.
</textSummary>
...
</forecast>
...etc
```

I am no good with programming, otherwise I would try and create a PR for it.

**Comment by glassbase** [comment]
I noticed you are capturing the text summary. Just not exposing it using the HA components. I am **going to attempt** to modify the sensor component to expose them.

**Comment by michaeldavie** [comment]
Sure, that should be pretty straightforward; it's similar to what I'm doing to get the next high and the overnight low from the forecast data.

**Comment by michaeldavie** [comment]
I've added both the period and text summary of the first forecast as current conditions. I'll work as exposing these as sensors in Home Assistant as well.

**Comment by michaeldavie** [comment]
I've made a PR with this feature: https://github.com/home-assistant/home-assistant/pull/24884/files
