### ISSUE TITLE
Air Quality Health Index 

### ISSUE THREAD

**Issue by jm66** [michaeldavie/env_canada#10]
Hi @michaeldavie, inspired by  `env_canada` and following the module architecture, I put together [aqhi_canada](https://github.com/jm66/aqhi_canada) which work pretty much the same as `env_canada`:

```
from aqhi_canada.aqhi_data import AqhiData

aqhi = AqhiData(coordinates=(lat, long), language='english')
aqhi.conditions
{'aqhi': {'label': 'Air Quality Health Index', 'value': '2.1'}}

aqhi = AqhiData(coordinates=(lat, long), language='french')
aqhi.conditions
{'aqhi': {'label': 'Cote air santé', 'value': '2.1'}}
```

But pulling data from different source [AQHI_XML_File_List.xml](http://dd.weather.gc.ca/air_quality/doc/AQHI_XML_File_List.xml), `http://dd.weather.gc.ca/air_quality/aqhi/{cgndb}/observation/realtime/xml/AQ_OBS_{lan}_CURRENT.xml` and `http://dd.weather.gc.ca/air_quality/aqhi/{cgndb}/observation/realtime/xml/AQ_FCST_{lan}_CURRENT.xml`.

At first I thought it could be a different package, but since the data comes from Environment Canada as well, I believe it could be part of the `env_canada`. Please, let me know your thoughts and if you agree to add `aqhi_data.py` - I could happily submit a PR.

**Comment by michaeldavie** [comment]
Cool! I think that it makes sense it add it, and I can add it to the `environment_canada` component for Home Assistant as well. PR away!

**Comment by jm66** [comment]
Thanks for merging the code. Please, let me know how I could help to add `aqhi` to the `environment_canada` component.

**Comment by michaeldavie** [comment]
I did some work on this today, and I think I'm going to merge the AQHI logic you developed into the existing `ec_data` file. That will make things simpler on the Home Assistant side, and I think it makes sense for the module as well. I'm going to try to work on this over the next next week; hopefully we'll get it into the 0.102 release, which is a little more than 3 weeks away.

**Comment by michaeldavie** [comment]
The AQHI data has been added to release v0.0.30, and I've opened a PR (https://github.com/home-assistant/home-assistant/pull/28487) to add an AQHI sensor to Home Assistant in 0.102.

**Comment by jm66** [comment]
Thanks a lot @michaeldavie im looking forward to adding the AQHI index to my alerts/notifications.
