### ISSUE TITLE
 Platform error camera.environment_canada - No module named 'bs4'

### ISSUE THREAD

**Issue by TheRealWaldo** [michaeldavie/env_canada#17]
Experiencing failures as it appears there is still code related to the module.

https://github.com/michaeldavie/env_canada/blob/6dd0dd338dc3fb5b62d5aedebc10a9931f1c325e/env_canada/ec_radar.py#L7

Also see:
https://community.home-assistant.io/t/breaking-change-to-environment-canada-integration-introduced-by-ha-0-107/180157/2

**Comment by michaeldavie** [comment]
Thanks, I'm working on an update that will address this.

**Comment by michaeldavie** [comment]
Closed via https://github.com/home-assistant/core/pull/36010
