### ISSUE TITLE
Add Language parameter

### ISSUE THREAD

**Issue by Deurnieur** [michaeldavie/env_canada#2]
Hi, 
  Is it possible to add a language parameter ?  (French or English)

English:
    XML_URL_BASE = 'http://dd.weatheroffice.ec.gc.ca/citypage_weather/xml/{}_e.xml'

French:
    XML_URL_BASE = 'http://dd.weatheroffice.ec.gc.ca/citypage_weather/xml/{}_f.xml'

Thanks

**Comment by michaeldavie** [comment]
Sure, I can take a look at this. Are you interested in exposing the French for Home Assistant, or just in general?

**Comment by Deurnieur** [comment]
French for Home Assistant

Thanks

**Comment by michaeldavie** [comment]
I added this in 0.0.12, and I'll work on adding it to Home Assistant as well. If you could test it, that would be great.

**Comment by Deurnieur** [comment]
Great!  I will tes it.

Thanks

**Comment by michaeldavie** [comment]
I've made a PR with this feature: https://github.com/home-assistant/home-assistant/pull/24884/files
