### ISSUE TITLE
Sensors Unknown or non-existent? 

### ISSUE THREAD

**Issue by ikifar2012** [michaeldavie/env_canada#20]
A lot of my environment Canada sensors show as Unavailable or Unknown, have I configured something incorrectly?
![image](https://user-images.githubusercontent.com/20800434/83982904-44550600-a8f8-11ea-8243-ea14faca64cc.png)

**Comment by michaeldavie** [comment]
It's likely that the station that's being used just doesn't have values for those sensors. If you open one of the sensors with data, what are the values for the `location` and `station` attributes?

**Comment by ikifar2012** [comment]
Toronto Buttonville Municipal Airport

**Comment by michaeldavie** [comment]
That seems consistent with what the page for that station is showing: https://weather.gc.ca/city/pages/on-85_metric_e.html. It was likely automatically selected as the closest to your location.

It looks like Pickering or Toronto might be your best bets for more complete data. You can override the automatic station selection as described in the documentation at https://www.home-assistant.io/integrations/environment_canada/. You could also have two copies of the integration running with different stations, if you wanted to use some data from each.

Let me know if you have any trouble.

**Comment by ikifar2012** [comment]
How do I have multiple copies of the integration?

**Comment by michaeldavie** [comment]
Like this, the first one will be the closest (Buttonville), then the second one will be Toronto.
```
sensor:
  - platform: environment_canada
  - platform: environment_canada
    station: ON/s0000458
```

**Comment by ikifar2012** [comment]
It seems now after adding the second sensor to my config my original sensors have gone unavailable
![image](https://user-images.githubusercontent.com/20800434/84218650-d8f86900-aa9c-11ea-935b-e81e551590ac.png)

**Comment by michaeldavie** [comment]
This might be due to the old entities existing in the entity registry...maybe try disabling the ones you don't want.

**Comment by ikifar2012** [comment]
it looks like the documentation is out of date because those were the entity id's listed however looking at my entity registry it seems the entity id's have been changed, I may make a PR to the docs if that is ok with you as it seems:

`sensor.pop` is now `sensor.chance_of_percip`
`sensor.text_summary` is now `sensor.forecast`
`sensor.precip_yesterday` is now `sensor.precipitation_yesterday`
`sensor.wind_dir` is now `sensor.wind_direction`
`sensor.low_temp` is now `sensor.low_temperature`
and `sensor.high_temp` is now `sensor.high_temperature`

**Comment by ikifar2012** [comment]
Draft for PR:
https://github.com/ikifar2012/home-assistant.io/commit/2e411c30cddcfe529624eebeb71f5b8b3a25c4c1

**Comment by ikifar2012** [comment]
I made the requested changes, if you have any more suggestions let me know:
https://github.com/ikifar2012/home-assistant.io/commit/8b60cd5ede61830180d152d03732ab2950f0c37e
