### ISSUE TITLE
Time progression on new map?

### ISSUE THREAD

**Issue by deftdawg** [michaeldavie/env_canada#24]
Wondering if there's a way to get time progression on there, it's can be difficult to tell what time we are actually looking at (2 hours ago or now).

Also maybe some kind of legend, I assume light blue is clouds and darker colours indicate precipitation?  

Otherwise the new weather map looks quite nice!  Really like that it's so much more detailed. 👍 

![image](https://user-images.githubusercontent.com/4991612/84820928-544fa280-afe8-11ea-8122-1d094ac237d6.png)

**Comment by michaeldavie** [comment]
Fixed in v0.0.41

**Comment by deftdawg** [comment]
Thanks, that  looks great!
