### ISSUE TITLE
geogratis is broken in new HA (.112) - using weak SSL (TLS1.0)

### ISSUE THREAD

**Issue by cpw** [michaeldavie/env_canada#25]
Hi, it looks like the base map layer server maps.geogratis.gc.ca is failing to work with HA .112, due to using weak SSL encryption (TLS 1.0).

I put the URL into my browser and it's showing this:
![image](https://user-images.githubusercontent.com/1217211/86271626-3878fe80-bb9b-11ea-923f-ad5bdf99bb77.png)

I'm guessing they tightened up the SSL in .112 somehow to cause this breakage?

Perhaps swap to using http, until the server figures out how to get into 2010?

Thanks!

**Comment by michaeldavie** [comment]
Yeah, it definitely looks like there are issues with the SSL configuration for the the map server: https://www.ssllabs.com/ssltest/analyze.html?d=maps.geogratis.gc.ca

However, I'm not getting any errors with the Docker version of 0.112. Can you provide me some more details on the installation you're using and the errors that you're seeing?

**Comment by cpw** [comment]
i'm using virtualenv on a homebrew debian buster container.

**Comment by michaeldavie** [comment]
Thanks, another venv user has reported the same issue. I've reached out to NRCan, but in the meantime I'll drop it back to HTTP.

**Comment by michaeldavie** [comment]
Update has been merged into `dev`.
