### ISSUE TITLE
Radar sites out of date

### ISSUE THREAD

**Issue by dougshields** [michaeldavie/env_canada#26]
I see Strathmore (aka Calgary) has the older XSM radar which was replaced by CASSM in November.

I found a replacement schedule posted at https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/radar-overview/modernizing-network.html#toc0 which you may want to keep handy, as there are replacements coming up in August, September, October, and November, and indeed into 2023.

Unfortunately I can't find a list of future site locations to suggest for pre-loading the new sites (presumably near the old sites, but that's just an assumption, and there are also new sites being added.

**Comment by michaeldavie** [comment]
Thanks for pointing this out. Since the map isn't tied to the station locations anymore I'm hoping to deprecate this list, so maybe this is a good reason to do it sooner rather than later.

**Comment by michaeldavie** [comment]
Radar sites are no longer supported.
