### ISSUE TITLE
Dependency on opencv caused home assistant to pull env_canada from its image

### ISSUE THREAD

**Issue by maruel** [michaeldavie/env_canada#32]
https://github.com/michaeldavie/env_canada/commit/602c906a7eee4e2b0a187f5e45a8d71df482df39 added a dependency on opencv-python-headless 4 months ago.

Then folks in home assistant commented out env_canada from requirements_all.txt in https://github.com/home-assistant/core/pull/38731 because they do not want to depend on opencv.

It'd be nice if env_canada could be added back as default to the docker container, which would require likely removing the opencv dependency.

Thanks

**Comment by michaeldavie** [comment]
Thanks, I didn't know about that change. However, it doesn't seem to cause any issues, whereas removing `opencv` would require removing or reworking the radar image processing. Does not having this library in the Docker image cause a problem?

**Comment by maruel** [comment]
I just wanted to be sure that you were aware in case you wanted to react.
OpenCV is a large library. I personally feel it is overkill for drawing text on an image; it's an computer vision library. The commit doesn't explain the rationale for the switch from PIL so I'm interested what caused you to write it in the first place.

re: docker, the [official image](https://hub.docker.com/r/homeassistant/home-assistant/) doesn't have gcc installed, so running something like `docker exec homeassistant pip install --target /config/deps env_canada` fails with `RuntimeError: Broken toolchain: cannot link a simple C program`.
I didn't mean to use this issue to have you debug my problems, that's orthogonal to the request.

**Comment by michaeldavie** [comment]
Hmmm, it looks like I should be able to do this with PIL, so I'll take another look at that.

I'm using the Docker image myself, and it loads the components from my `configuration.yaml` without any manual tinkering required.

```
weather:
  - platform: environment_canada

camera:
  - platform: environment_canada

sensor:
  - platform: environment_canada
```

**Comment by maruel** [comment]
re: PIL Ok thanks, so I'll keep this issue open then.

re docker: I stuck to 0.113.3 in the meantime. That's really not env_canada specific though so I don't want to waste your time on this, I'll do my homework.

**Comment by michaeldavie** [comment]
Fixed by da0095a

**Comment by maruel** [comment]
Thanks!

**Comment by michaeldavie** [comment]
No problem, thanks for pointing this out. It's already been merged, so the change will be in Home Assistant 0.118.
