### ISSUE TITLE
Suggest adding normal lows and highs for given location

### ISSUE THREAD

**Issue by PhilBaobab** [michaeldavie/env_canada#34]
Hi,

As the title states, it would be useful to include the selected station's normal high and low temperature. I'm not sure what the high and low temperature contained in the `ec_en.conditions` function refer to. They do not seem to match the high/low normals published on EC Canada's web site for the selected station.

Thank you .

Baobab

**Comment by michaeldavie** [comment]
`high_temp` and `low_temp` are the next forecasted high and low temperature, not the normals: https://github.com/michaeldavie/env_canada/blob/6b3a2ce0ad6e5ddf9d18f46a66afcd658c01386c/env_canada/ec_weather.py#L82-L91.

It looks like the normal values are (at least sometimes) in the XML data though, so I should be able to add these. Thanks for the suggestion!

**Comment by PhilBaobab** [comment]
Awesome. Thank you. Just looking at the XML file from ec Canada now and it looks like the norms are there.

**Comment by michaeldavie** [comment]
Fixed in https://github.com/michaeldavie/env_canada/commit/2fa9331f4c23295fb10ea8d1fa30d417335af490
