### ISSUE TITLE
Looking for documentation on use of ec_en.update()

### ISSUE THREAD

**Issue by PhilBaobab** [michaeldavie/env_canada#35]
Hello,

Is there a place I can find documentation about what purpose `ec_en.update()`serves and when/how to use it. I seem to be able to make use of everything else without using it at all in my script. Am I missing something?

Thank you,

Baobab

**Comment by michaeldavie** [comment]
As of v0.3.0, `update()` is the function that fetches the data. Would you mind posting your script?
