### ISSUE TITLE
weather.gc.ca schema has changed

### ISSUE THREAD

**Issue by Kotove** [michaeldavie/env_canada#37]
https://dd.weather.gc.ca/citypage_weather/xml/siteList.xml
it now includes a provincial code, so URL and maybe some station selection logic should be updated.

**Comment by michaeldavie** [comment]
I'm using the list from https://dd.weather.gc.ca/citypage_weather/docs/site_list_en.csv (which includes the province codes), but from the timestamps at https://dd.weather.gc.ca/citypage_weather/docs/ it doesn't look like anything has changed. Everything seems to be working so I don't think there's an issue, but if something is not working please let me know.

**Comment by Kotove** [comment]
yeah, I shoulde.ve added more details. 
The current code polls URL: WEATHER_URL = "https://dd.weather.gc.ca/citypage_weather/xml/{}_{}.xml"
while actual xml is now located under province folders, like:
https://dd.weather.gc.ca/citypage_weather/xml/QC/s0000029_f.xml

**Comment by michaeldavie** [comment]
It might be a bit convoluted in the code, but this is already taken into account when `self.station_id` is determined: 

https://github.com/michaeldavie/env_canada/blob/e1041fcf296f62383381aa8289b15de051558f94/env_canada/ec_weather.py#L185

This is then used with `self.language` to populate the URL:

https://github.com/michaeldavie/env_canada/blob/e1041fcf296f62383381aa8289b15de051558f94/env_canada/ec_weather.py#L220

**Comment by Kotove** [comment]
agree, thank you. I missed the correct notation of station id along with provincial code in the example, `ec_fr = ECWeather(station_id='ON/s0000430', language='french')` now it's clear
