### ISSUE TITLE
Add historical climate data

### ISSUE THREAD

**Issue by darrenwiens** [michaeldavie/env_canada#39]
Would you be open to a pull request for a historical data download class (i.e. `ECHistorical`)?

The data would come from: https://climate.weather.gc.ca/historical_data/search_historic_data_e.html

Specifically, downloading from: https://climate.weather.gc.ca/climate_data/bulk_data_{e|f}.html

I see the other modules download from `https://dd.weather.gc.ca/`. I don't see historical data in there, but if you know where I might find that, I'd be happy to use that instead.

**Comment by ConsultantYD** [comment]
I second this comment. env_canada is an awesome package and having easy native access to historical data would multiply the application possibilities.

Let me know if I can be of any help in the process or in the review.
