### ISSUE TITLE
"Weather" element showing "Condition not observed" in card title

### ISSUE THREAD

**Issue by alexandery** [michaeldavie/env_canada#4]
Not sure why that caption is there and what to do to fix that. Don't see any details on that in the docs.

**Comment by michaeldavie** [comment]
Do you know what station you're using? This value is returned if the station hasn't reported a condition, e.g. https://weather.gc.ca/city/pages/nu-24_metric_e.html

**Comment by alexandery** [comment]
I'm using custom defined station as per your instructions. However, does it make sense to remove "Not observed" as that has no value whatsoever? Could be a simple enough rule to filter that out?

**Comment by michaeldavie** [comment]
I suppose I could just set it as `null`, though I’m not sure what that will show up as in the UI.

If you’re using a station with no observations, are you using the weather component only for the forecast aspect?

**Comment by alexandery** [comment]
Weather component for the forecast and Sensor for details of the current conditions.

And no, seems that my station doesn't support "conditions". So, if there is a way to not display that label - that'd be one way to go.

**Comment by deftdawg** [comment]
I was about to open a bug for Home Assistant for this very issue... I'll add my comment here instead.

It looks like a lot of stations do not take observations at all...  including the one closest to me. 

Markham, Ontario (i.e. https://weather.gc.ca/city/pages/on-85_metric_e.html)

My suggestion is if possible, when "Condition not observed" is the data, it might be nicer to use the value from the hourly forecast instead -- i.e. https://weather.gc.ca/forecast/hourly/on-85_metric_e.html

**Comment by michaeldavie** [comment]
That's a great idea, I should be able to work that in without too much trouble. Thanks!

**Comment by deftdawg** [comment]
Here's the Xpath query to get the first hourlyForecast element:
```xpath
//hourlyForecastGroup/hourlyForecast[1]
```

**Comment by michaeldavie** [comment]
Thanks, but it's even easier; the `env_canada` library already returns a `dict` with the forecast icon codes and temperatures. I just need to use them if the data is missing.

**Comment by michaeldavie** [comment]
Fixed!

<img width="525" alt="Screenshot 2019-07-11 23 27 11" src="https://user-images.githubusercontent.com/16008714/61100286-aaf54980-a433-11e9-8965-3ffd2c0121e3.png">

**Comment by deftdawg** [comment]
Eh? Did you push the commit?  I don't see it in the repo.

**Comment by michaeldavie** [comment]
https://github.com/michaeldavie/home-assistant/commit/93f9be333a47e2ea746d304c690c48084ec3e270

**Comment by michaeldavie** [comment]
Thanks, I noticed this issue as well. The forecasts weren't being updated correctly, so I've fixed this in 0.0.25. I just opened a PR to merge this change into Home Assistant, and hopefully it'll make it into 0.99.
