### ISSUE TITLE
Make station ID name available

### ISSUE THREAD

**Issue by gwww** [michaeldavie/env_canada#43]
For naming entities in HA it would be nice to automatically be able to use the text name associated with the station. A simple property would suffice.

**Comment by michaeldavie** [comment]
Both the location and station name are available via the `metadata` property, once the object has been updated:
```
In [6]: test = ECWeather(coordinates=(50, -100))

In [7]: asyncio.run(test.update())

In [8]: test.metadata
Out[8]: 
{'timestamp': datetime.datetime(2021, 9, 6, 15, 0, tzinfo=tzutc()),
 'location': 'Brandon',
 'station': 'Brandon Airport'}
```

**Comment by gwww** [comment]
Excellent! Missed that looking through the code.

**Comment by michaeldavie** [comment]
That's what I'm using for the name currently:

https://github.com/michaeldavie/hass_environment_canada/blob/9a2e34212f8fb8dc3c4f2e3c99ab3e6d6ab6915f/weather.py#L82
