### ISSUE TITLE
Sensors titles are badly formatted in the UI

### ISSUE THREAD

**Issue by alexandery** [michaeldavie/env_canada#5]
So, weather sensor requires a name to be able to reference sub-sensors. The name must be something with no spaces, etc. - pretty much some programmatic name. But the sensors display names include main weather sensor name, which makes it look very ugly. Example:
```
- sensor
  name: my_weather_sensor
```
results in display names like: ``` my_weather_name Temperature``` in the UI.

Either add a display name or do not add the main sensor name into titles.

**Comment by michaeldavie** [comment]
You don't have to provide a value for `name` in `configuration.yaml`, the default behaviour is `null`, e.g. `sensor.temperature`. If you want to change what's displayed in the UI, you can override this by setting a `friendly_name`, typically in `customize.yaml`. See https://www.home-assistant.io/docs/configuration/customizing-devices/.

**Comment by michaeldavie** [comment]
This is a good point, the behaviour is different than I expected. I've changed the code so that the `entity_id` for each sensor will match the keys in the documentation, while the name displayed in the UI will be the English or French label. Thanks for pointing this out!

**Comment by alexandery** [comment]
Thanks for adjusting your code to address this aspect. Hope it'll get merged with no further questions that I see in that thread.
