### ISSUE TITLE
Snow radar all white

### ISSUE THREAD

**Issue by gwww** [michaeldavie/env_canada#51]
0.5.14 snow radar has nothing showing except white box and legend. No, there's no blizzard; 

![Screen Shot 2021-11-04 at 11 43 06](https://user-images.githubusercontent.com/3060128/140365731-1bbefeb0-5951-41cf-be36-3eb89705f623.png)
)

**Comment by michaeldavie** [comment]
I wonder if this is related to the change to the `update()` function.

![image](https://user-images.githubusercontent.com/16008714/140416033-218549bd-89f3-4482-82fa-2d6c5120cce5.png)

**Comment by gwww** [comment]
Rain radar works so I didn’t think that change would be affecting.

**Comment by michaeldavie** [comment]
Testing with the bare v0.5.15 code seems to work okay. Maybe the white background was caused by a failure of the map to return correctly?

**Comment by gwww** [comment]
I'll monitor over the next week.

**Comment by gwww** [comment]
I'm going to close this. I'm guessing my environment is broken, at least the stuff that does the graphic manipulation. I just did a rebuild and there were build challenges with the graphic bits. Even though it built I think it is suspect.
