### ISSUE TITLE
mocking of unit tests accessing production services

### ISSUE THREAD

**Issue by tomkralidis** [michaeldavie/env_canada#54]
(disclaimer: I'm the architect of the [ECCC/MSC GeoMet API platform](https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/weather-tools-specialized-data/msc-geomet-api-geospatial-web-services.html), which provides some of the data/services used in this project).

Great work here!  If possible, it would be valuable to implement test data/mocking as part of the tests so as not to test against production/operational instances.

**Comment by michaeldavie** [comment]
Thanks for the suggestion. Is there a problem with testing against the live system? The tests are not volumetric and are typically only ran when new commits are made.

**Comment by tomkralidis** [comment]
Mostly a suggestion in the case that the code is used/tested beyond this repo.
