### ISSUE TITLE
Alternate base map provider

### ISSUE THREAD

**Issue by khorovatin** [michaeldavie/env_canada#56]
Would it be possible to allow specifying an alternate base map provider to ECRadar for those times (like now) that geogratis.gc.ca is down? 
Perhaps openstreetmap.org?

**Comment by deftdawg** [comment]
Looks like there's a fix already committed... https://github.com/michaeldavie/env_canada/commit/d33b4a8183a1618b9baf66abf954a9cd1bd45926

Gotta either hang in until it lands in HA (2021.12.2?) or make a clone of the env_canada component in the custom_components folder, add a version and bump the env_canada dependency version to this new updated version.

**Comment by michaeldavie** [comment]
I've added Mapbox as a fallback option in v0.5.20.

**Comment by khorovatin** [comment]
Awesome, thanks!
