### ISSUE TITLE
Feature Request - Add Yesterday's High/Low Temperature

### ISSUE THREAD

**Issue by databoy2k** [michaeldavie/env_canada#62]
Would you be willing to add new conditions to ec_weather.py that pull yesterday's high and low temperatures? I assume that it would look something like: 

    "high_temp_yesterday": {
        "xpath": "./yesterdayConditions/temperature[@class="high"]",
        "type": "int",
        "english": "High Temperature Yesterday",
        "french": "Haute température d'hier",
    }
    "low_temp_yesterday": {
        "xpath": "./yesterdayConditions/temperature[@class="low"]",
        "type": "int",
        "english": "Low Temperature Yesterday",
        "french": "Basse température d'hier",
    }

I use your library through your Home Assistant component, and one of the functions that I'm trying to accomplish is the ability to compare yesterday's high temperature to today's forecasted high. Obviously, it's easy to get today's forecasted high, but I can't for the life of me get yesterday's without storing it in an additional helper.

So, if possible, could those two new conditions become sensors in the HA side as well? 

Happy to run a test once the changes are merged to make sure it's working.

Thanks!

**Comment by michaeldavie** [comment]
Fixed in release v0.5.24. I'll work on a PR to add these to HA.

**Comment by databoy2k** [comment]
Just following up on this; did that HA PR ever happen and I missed it? I didn't see any commits.
