### ISSUE TITLE
Historical hourly data

### ISSUE THREAD

**Issue by ConsultantYD** [michaeldavie/env_canada#63]
Would it be possible to add the hourly granularity to the ECHistorical class ?

**Comment by michaeldavie** [comment]
@darrenwiens, what do you think?

**Comment by Biorix** [comment]
I thought I added that with my PR
You can now pass timeframe as argument :
`ec_fr_csv_20 = ECHistorical(station_id=station_id, year=2020, language="french", format="csv", timeframe=1)`
But there's an issue with the code I pushed

You get hourly granularity, but just for the wrong year and just one month... 

Sorry about that, I'll look into it

**Comment by michaeldavie** [comment]
Closed by #64
