### ISSUE TITLE
Support hourly wind forecast

### ISSUE THREAD

**Issue by cpw** [michaeldavie/env_canada#66]
Currently, you don't capture the hourly wind forecast, that is available from the XML: e.g: https://dd.weather.gc.ca/citypage_weather/xml/ON/s0000623_e.xml - wind and direction seem to be available broadly across stations.

It'd be nice if you could make that available up through the home assistant layer. Thanks!

**Comment by michaeldavie** [comment]
Thanks, it looks like there are a couple values that I'm not currently pulling out. I can add them to the library easily enough, but surfacing them to HA in a useful way will be trickier.

**Comment by michaeldavie** [comment]
Do you think it would be useful to have the forecasted wind speed and direction for the next hour available as sensors in HA?

**Comment by michaeldavie** [comment]
Fixed in 1321996
