### ISSUE TITLE
Connection failed to dd.meteo.gc.ca

### ISSUE THREAD

**Issue by Patrickcob** [michaeldavie/env_canada#68]
Not sure if  the IP of the API changed or its only a temporary down state, but the dd.meteo.gc.ca or '205.189.10.47', 443 address seems  down.

**Comment by michaeldavie** [comment]
Weird, it seems to work in the browser but not from the terminal.

**Comment by Patrickcob** [comment]
Does weather canada provide updates if they are doing maintenance on their API?

**Comment by alexandreleroux** [comment]
@Patrickcob , the [MSC Open Data](https://eccc-msc.github.io/open-data/) API looks fine (MSC GeoMet), but I'm indeed also having trouble accessing the flat file server (MSC Datamart). Both services are supported 24/7, thus I expect someone is looking at it already. 

When downtime occurs during business hours, users are informed through the dd_info list for MSC Datamart, and the GeoMet-Info list for MSC GeoMet. See link to public documentation (above). Hope this helps.
