### ISSUE TITLE
Sunrise / sunset data

### ISSUE THREAD

**Issue by infectedroot** [michaeldavie/env_canada#69]
I can't seem to find how I can extract sunrise or sunset data from this code. I have taken some time to pour through it and it looks like there might not be anything.

Has anyone been able to accomplish this / point me in the right direction?

**Comment by michaeldavie** [comment]
I'm not currently extracting that data, but it looks like it is available in the XML file: https://dd.weather.gc.ca/citypage_weather/xml/ON/s0000430_e.xml

Feel free to open a PR to add this, or I can add it to the backlog.

**Comment by infectedroot** [comment]
Done deal, @michaeldavie. Check it out and let me know what you think.

**Comment by michaeldavie** [comment]
Thanks!
