### ISSUE TITLE
'cannot identify image file' error while creating radar loop

### ISSUE THREAD

**Issue by stevendinardo** [michaeldavie/env_canada#71]
It looks like Environment and Climate Change Canada changed the time intervals available for the radar layers but the code assumes 10 minutes intervals. https://github.com/michaeldavie/env_canada/blob/470f8df2bb2573cad3dda8db183a5cb24a249018/env_canada/ec_radar.py#L338
The an example dimension string from the GeoMet WMS.
"2023-01-30T22:12:00Z/2023-01-31T01:12:00Z/PT6M"
The PT6M indicating there is a 6 minute time interval avalabile for this layer.

The 10 minute assumption in the code makes the server return with an XML saying time is outside valid hours which causes https://github.com/michaeldavie/env_canada/blob/470f8df2bb2573cad3dda8db183a5cb24a249018/env_canada/ec_radar.py#L257 to create the error "PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f2dfc95d030>"

**Comment by alexandreleroux** [comment]
@stevendinardo , I confirm, radar layers are now at the 6-minutes interval as per public announcement: https://lists.ec.gc.ca/pipermail/geomet-info/2023-January/000111.html 

By the way, there's a new radar extrapolation layer now! Currently up to 1h in the future. As well as a radar surface precipitation type layer. Hope this helps :-)

**Comment by michaeldavie** [comment]
Thanks for flagging this. I'll work on the immediate fix, and see about making use of the extrapolation too.

**Comment by michaeldavie** [comment]
Fixed in v0.5.27

**Comment by stevendinardo** [comment]
Awesome. It might make sense in the future to have it dynamically grab the interval from the dimension string in case it changes again.
