### ISSUE TITLE
error fetching environment_canada AQHI data

### ISSUE THREAD

**Issue by rcblackwell** [michaeldavie/env_canada#72]
The problem
Unexpected error fetching environment_canada AQHI data: invalid literal for int() with base 10:

What version of Home Assistant Core has the issue?
2023.2.4

What was the last working version of Home Assistant Core?
2023.2.3

What type of installation are you running?
Home Assistant Supervised

Integration causing the issue
Environment Canada

Link to integration documentation on our website
https://www.home-assistant.io/integrations/environment_canada

Diagnostics information
[config_entry-environment_canada-90973edac7407b00e2058536d993fb26.json.txt](https://github.com/home-assistant/core/files/10725140/config_entry-environment_canada-90973edac7407b00e2058536d993fb26.json.txt)

Example YAML snippet
No response

Anything in the logs that might be useful for us?
Logger: homeassistant.components.environment_canada
Source: components/environment_canada/__init__.py:117
Integration: Environment Canada (documentation, issues)
First occurred: 1:06:34 PM (2 occurrences)
Last logged: 1:11:34 PM

Unexpected error fetching environment_canada AQHI data: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/environment_canada/__init__.py", line 117, in _async_update_data
    await self.ec_data.update()
  File "/usr/local/lib/python3.10/site-packages/env_canada/ec_aqhi.py", line 212, in update
    self.forecasts["daily"][period] = int(
ValueError: invalid literal for int() with base 10: ''

Additional information

The error appeared in my HA logs after updating from version 2023.2.3 to 2023.2.4:

This error was also reported at https://github.com/home-assistant/core/issues/88027

**Comment by michaeldavie** [comment]
I'm not planning to fix this unless it becomes a persistent problem.
