### ISSUE TITLE
error fetching environment_canada weather data

### ISSUE THREAD

**Issue by claudegel** [michaeldavie/env_canada#74]
[homeassistant.components.environment_canada] Unexpected error fetching environment_canada weather data: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/environment_canada/__init__.py", line 117, in _async_update_data
    await self.ec_data.update()
  File "/usr/local/lib/python3.10/site-packages/env_canada/ec_weather.py", line 381, in update
    if self.metadata["timestamp"] < max_age:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
home assistant version 2023.2.5
was working in version 2023.2.3

**Comment by michaeldavie** [comment]
Thanks, it seems that Environment Canada keeps coming up with new ways to return bad data.

**Comment by michaeldavie** [comment]
I've added code to handle this in #[301ad5a](https://github.com/michaeldavie/env_canada/commit/301ad5a5e203adf87d9cde907d3b1fc17a84d201), but I think I'll hold off on a release and PR for Home Assistant.

**Comment by claudegel** [comment]
Thank you for correcting this . I'll wait for the next HA  update

**Comment by michaeldavie** [comment]
This fix was included in release v0.5.29, which was included in Home Assistant 2023.3.0.

https://github.com/home-assistant/core/pull/88821
