### ISSUE TITLE
Unable to get the get_historical_stations 

### ISSUE THREAD

**Issue by rishbruh** [michaeldavie/env_canada#75]
Upon importing ECHistorical and get_historical_stations, the following errors pop up - 
1. NameError: name 'get_historical_stations' is not defined
2. ImportError: cannot import name 'get_historical_stations' from 'env_canada' (/usr/local/lib/python3.8/dist-packages/env_canada/__init__.py)

Have tried out pip install, !pip install and !apt install.

**Comment by michaeldavie** [comment]
It does seems like an environment issue; it looks like you're using a Jupyter notebook?

Take a look at the test code to see if that helps: https://github.com/michaeldavie/env_canada/blob/master/tests/test_ec_historical.py

**Comment by CourchesneA** [comment]
I had the same error, with or without a notebook. Using the following import solved it for me:
`from env_canada.ec_historical import get_historical_stations`
