### ISSUE TITLE
2023.4.0b6 Weather bulletins not showing up for Ottawa ( Kanata - Orleans)

### ISSUE THREAD

**Issue by pgsylvestre** [michaeldavie/env_canada#76]
After the latest beta release, active weather bulletins no longer show up. 

![image](https://user-images.githubusercontent.com/61101978/229915700-96874e68-76ae-4965-82b6-8cd13092a50e.png)

**Comment by pgsylvestre** [comment]
Now they do. May have been an EC Datamart issue.

**Comment by michaeldavie** [comment]
Weird, I'm seeing the same with 2023.3.6, also in Ottawa. I'll close this for now since it seems like a data issue.

**Comment by alexandreleroux** [comment]
@michaeldavie if the source data is the Citypage Weather XMLs, then yes, potentially the data issue mentioned here: https://lists.ec.gc.ca/pipermail/dd_info/2023-March/000575.html Hope this helps :-)

**Comment by michaeldavie** [comment]
Thanks, I wasn't aware of this list but now I've signed up!
