### ISSUE TITLE
EC Radar Test fails 

### ISSUE THREAD

**Issue by fitzb** [michaeldavie/env_canada#82]
The imageio dependency should be >=2.28.0 to support the mode="RGBA" in ec_radar.py on line 364.

I had imageio 2.27.0 installed. Update env_canada and radar broke. Ran the pytests and the ec_radar test failed. Update imageio to 2.28.0 tests now pass.

**Comment by iamannalynleynes1206** [comment]
Good Job! Patience is a Virtue! Kudos!

**Comment by michaeldavie** [comment]
Thanks, fixed in 932914dda123d7413f9a9dee536837add58300fa
