### ISSUE TITLE
name: - why remove it?

### ISSUE THREAD

**Issue by glassbase** [michaeldavie/env_canada#9]
Most weather platforms have name. 

Name gave me (and I am sure others) an easy way to find and maintain sensors. Specifically, I could use the auto-entities Lovelace card and use the sensor.city_name_* to make a card of all my weather sensors

**Comment by michaeldavie** [comment]
This was another architectural decision, I believe that the thinking was that entities can be renamed in the entity registry if needed.

It looks like `lovelace-auto-entities` card can filter based on attribute, so you should be able to achieve the same result by filtering based on the `attribution` attribute that is populated with "Data provided by Environment Canada" in each sensor.
